FROM node:18 AS build

WORKDIR /app

COPY ./frontend_eng/music_academy/package*.json ./


RUN npm install

COPY ./frontend_eng/music_academy/ .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
